name: 'Github Pages Deployment'

on:
  workflow_dispatch:
  push:
    paths:
      - '**.yml'
  schedule:
    - cron: '00 2 4,20 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './site/'
        
    steps:
      - name: 'github / checkout'
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: 'ruby / setup / squarkdown'
        uses: ruby/setup-ruby@v1
        with:
          working-directory: './.stranger-quarkdown/'
          bundler-cache: true

      - name: 'squarkdown'
        run: |
          npm run squarkx
      
      - name: 'ruby / setup / prep'
        uses: ruby/setup-ruby@v1
        with:
          working-directory: './site/prep/'
          bundler-cache: true

      - name: 'prep'
        run: |
          npm run export

      - name: 'node / setup'
        uses: actions/setup-node@v6
        with:
          node-version: 'latest'
          cache: 'npm'
          cache-dependency-path: './site/package-lock.json'

      - name: 'svelte / npm install'
        run: |
          npm install

      - name: 'svelte / npm run build'
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: |
          npm run build

      # FIXME awaiting patch
      # - name: 'svelte / npm run test'
      #   run: |
      #     npx playwright install
      #     npm run test

      - name: 'github / upload artifacts'
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site/build/'

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: 'github / deploy'
        id: deployment
        uses: actions/deploy-pages@v4
